// Code generated by goctl. DO NOT EDIT!
// Source: register.proto

package server

import (
	"context"

	"chative-server-go/rpcserver/internal/logic"
	"chative-server-go/rpcserver/internal/svc"
	"chative-server-go/rpcserver/pb"
)

type RegiterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRegiterServer
}

func NewRegiterServer(svcCtx *svc.ServiceContext) *RegiterServer {
	return &RegiterServer{
		svcCtx: svcCtx,
	}
}

func (s *RegiterServer) SendSMS(ctx context.Context, in *pb.SendSMSRequest) (*pb.SendSMSResponse, error) {
	l := logic.NewSendSMSLogic(ctx, s.svcCtx)
	return l.SendSMS(in)
}

func (s *RegiterServer) VerifySMS(ctx context.Context, in *pb.VerifySMSRequest) (*pb.VerifySMSResponse, error) {
	l := logic.NewVerifySMSLogic(ctx, s.svcCtx)
	return l.VerifySMS(in)
}
